### ISSUE TITLE
Fails to add to GUI after creating automation

### ISSUE THREAD

**Issue by Node815** [Aohzan/hass-blueprints#1]
This creates the entry into the automation.yaml file but the automation does not show up in the GUI or trigger when running.   Home Assistant provides the following error:

Blueprint Advanced medication reminder generated invalid automation with inputs OrderedDict([('reminder_time', '10:00:00'), ('notify_device', '65f01c64a9dd6df8fe29a1521c3cc3a7'), ('input_boolean', 'ammedskeith'), ('optional_action', [])]): not a valid value for dictionary value @ data['action'][0]['target']['entity_id']. Got None

I am not sure what the problem is - can you please advise?

**Comment by Aohzan** [comment]
Can you give me the code you use for the blueprint ?

**Comment by Node815** [comment]
I used the one linked in the post here: 
https://community.home-assistant.io/t/advanced-medication-reminder/300137
It's marked "import blueprint"

https://my.home-assistant.io/redirect/blueprint_import/?blueprint_url=https%3A%2F%2Fraw.githubusercontent.com%2FAohzan%2Fhass-blueprints%2Fmain%2Fblueprints%2Fmedication_reminder.yaml

I also tried the other one which links to this page:
https://github.com/Aohzan/hass-blueprints

**Comment by Aohzan** [comment]
when you use the blueprint, what do you put in `optional_action` ?

**Comment by Node815** [comment]
Nothing - As it says "Optional Action" on the prompt, I figured it was not required. :) 

I should note, that it does add to the "Automations.yaml" file though.  This is the content of what it wrote:

```
mode: single
- id: '1654032167229'
  alias: Advanced medication reminder
  description: 'Medication Reminder'
  use_blueprint:
    path: Aohzan/medication_reminder.yaml
    input:
      reminder_time: '10:00:00'
      notify_device: 65f01c64a9dd6df8fe29a1521c3cc3a7
      input_boolean: Medalert
```

**Comment by Aohzan** [comment]
Can you try to set an action ?

**Comment by Node815** [comment]
If you mean "Optional Action"  here:
```
- id: '1654033342398'
  alias: Advanced medication reminder
  description: Test Reminder for debug
  use_blueprint:
    path: Aohzan/medication_reminder.yaml
    input:
      reminder_time: 00:00:00
      notify_device: 65f01c64a9dd6df8fe29a1521c3cc3a7
      input_boolean: MedminderAM
      optional_action:
      - delay:
          hours: 0
          minutes: 10
          seconds: 0
          milliseconds: 0

```

**Comment by Aohzan** [comment]
you put `delay` in `optional_action`, right ?

**Comment by Node815** [comment]
I put a 10 minute delay as you asked me to put something there, so I chose that as a value.

**Comment by Aohzan** [comment]
and it works ?

**Comment by Node815** [comment]
No.  As stated before, it adds to automations.yaml but fails to appear in the Automations menu itself in HASSIO.

**Comment by Aohzan** [comment]
Same error in logs ?

**Comment by Node815** [comment]
Pretty much the same error, but this is the latest from now when I tried it.  I reported the original error several HASSIO versions back, I am on the most recent one:

Logger: homeassistant.components.automation
Source: components/automation/__init__.py:651
Integration: Automation (documentation, issues)
First occurred: 7:01:31 AM (3 occurrences)
Last logged: 7:01:31 AM

> Blueprint Advanced medication reminder generated invalid automation with inputs OrderedDict([('reminder_time', '10:00:00'), ('notify_device', '65f01c64a9dd6df8fe29a1521c3cc3a7'), ('input_boolean', 'Medalert')]): not a valid value for dictionary value @ data['action'][0]['target']['entity_id']. Got None
> Blueprint Advanced medication reminder generated invalid automation with inputs OrderedDict([('reminder_time', '00:00:00'), ('notify_device', '65f01c64a9dd6df8fe29a1521c3cc3a7'), ('input_boolean', 'MedminderAM'), ('optional_action', [OrderedDict([('delay', OrderedDict([('hours', 0), ('minutes', 10), ('seconds', 0), ('milliseconds', 0)]))])])]): not a valid value for dictionary value @ data['action'][0]['target']['entity_id']. Got None
> Blueprint Advanced medication reminder generated invalid automation with inputs OrderedDict([('reminder_time', '10:00:00'), ('notify_device', '65f01c64a9dd6df8fe29a1521c3cc3a7'), ('input_boolean', 'Test2'), ('optional_action', [OrderedDict([('repeat', OrderedDict([('count', 2), ('sequence', [])]))])])]): not a valid value for dictionary value @ data['action'][0]['target']['entity_id']. Got None

**Comment by Aohzan** [comment]
If I look one of my blueprint call
```
  use_blueprint:
    path: Aohzan/medication_reminder.yaml
    input:
      reminder_time: input_datetime.sante_rappel_prise_de_medicament_soir
      notify_device: 1f60677561764fbebbeef7bc71c69935
      input_boolean: input_boolean.sante_medic
      optional_action:
        - service: script.notify_speaker
          data:
            message: "Rappel de prise de médicaments
```
your input_bollean is not correct
