### ISSUE TITLE
Notification actions not doing anything (Android)

### ISSUE THREAD

**Issue by modem7** [Aohzan/hass-blueprints#11]
Heya, 

It seems that the notification actions aren't doing anything on Android (OnePlus). 

It doesn't open the app if I click on the options (only on the main notifications), and I can't see anything in the logs that would indicate that those actions are being logged. 

![image](https://github.com/Aohzan/hass-blueprints/assets/4349962/65dfb07c-8cf7-43ea-ad02-2835a176eebe)

```yaml
alias: Medication reminder (Alex)
description: ""
use_blueprint:
  path: Aohzan/medication_reminder_android.yaml
  input:
    reminder_time: "23:00:00"
    notify_device: c04a27331390c64d531ab2d188a49e2e
    input_boolean: input_boolean.alex_medication_boolean
    optional_action: []
```

Two different phones are having this particular behaviour.
