### ISSUE TITLE
Error in 'choose[0]' evaluation: In 'template' condition: UndefinedError: 'None' has no attribute 'event'

### ISSUE THREAD

**Issue by Bhozar2** [Aohzan/hass-blueprints#4]
```
@Logger: homeassistant.helpers.script
Source: helpers/script.py:409
 First occurred: 22:30:00 (3 occurrences)
Last logged: 22:30:00

 Error in 'choose[0]' evaluation: In 'template' condition: UndefinedError: 'None' has no attribute 'event' 
```

```
Logger: homeassistant.helpers.template
Source: helpers/template.py:536
First occurred: 22:30:00 (3 occurrences)
Last logged: 22:30:00

Template variable error: 'None' has no attribute 'event' when rendering '{{ wait.trigger.event.data.actionName == 'taken' }}'
Template variable error: 'None' has no attribute 'event' when rendering '{{ wait.trigger.event.data.actionName == 'later' }}'
Template variable error: 'None' has no attribute 'event' when rendering '{{ wait.trigger.event.data.actionName == 'skip' }}'
```

My Automation
```
- id: '1667946269544'
  alias: medication jon
  description: ''
  use_blueprint:
    path: Aohzan/medication_reminder_ios.yaml
    input:
      reminder_time: '22:25:00'
      notify_device: 930fc2b96b822afa942def34c7d2ad88
      input_boolean: input_boolean.medicationjon
      ask_later_wait_time: 5
```

Using the blueprint IOS
