### ISSUE TITLE
FR: Recommended Combining Blueprints into One

### ISSUE THREAD

**Issue by kreene1987** [Aohzan/hass-blueprints#6]
From another blueprint if you add a toggle;

```
  input:
    is_ios:
      name: Is it an iOS device?
      description: Toggle if your selected device runs iOS, default is Android
      selector:
        boolean: {}
      default: false
```
Then variable:

```
variables:
  is_ios: !input 'is_ios'
```

Then define the data based on:

```
- device_id: !input 'notify_device'
  domain: mobile_app
  type: notify
  title: '{{ notification_title }}'
  message: '{{ notification_message }}'
  data: '{% set android_data = {"image": "%s"} | format(snapshot_access_file_path)
    %} {% set ios_data = {"attachment": {"url": "%s", "content_type": "JPEG"}} | format(snapshot_access_file_path)
    %} {{ ios_data if is_ios else android_data }}'
```
